
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Catalog of supported transcription engines and models.
 */
async getTranscriptionCatalog() : Promise<Result<TranscriptionCatalog, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcription_catalog") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check whether the selected transcription model is downloaded and loaded.
 */
async getModelStatus(selection: TranscriptionProfileSelection) : Promise<Result<TranscriptionRuntimeStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_status", { selection }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download the selected transcription model.
 * Progress is streamed back via the Channel API.
 */
async downloadModel(selection: TranscriptionProfileSelection, channel: TAURI_CHANNEL<DownloadProgress>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { selection, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a downloaded model from disk.
 */
async deleteModel(selection: TranscriptionProfileSelection) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { selection }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load the model into memory (GPU/CPU). Must be called after download.
 * The engine actor creates the engine, swaps out any previous one, and
 * loads the weights — all on its own thread.
 */
async loadModel(selection: TranscriptionProfileSelection) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_model", { selection }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start streaming transcription.
 * 
 * `async` + `spawn_blocking`: the engine-reset reply can take 0.5–2s, so the
 * blocking wait runs off-thread and the window never freezes.
 */
async startTranscription(channel: TAURI_CHANNEL<TranscriptionSegment>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_transcription", { channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop streaming transcription.
 * 
 * Awaits the drain so the frontend's assembled transcript (used for clipboard
 * and dictation history) is complete before this resolves. The drain runs in
 * `spawn_blocking`, so awaiting it does not freeze the window.
 */
async stopTranscription() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_transcription") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List available audio input devices
 */
async listAudioDevices() : Promise<Result<AudioDeviceInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_audio_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Select an audio input device by name
 */
async selectAudioDevice(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("select_audio_device", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Debug: feed the debug WAV through the engine to test model in isolation.
 */
async testTranscribeWav() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_transcribe_wav") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Copy text to clipboard and simulate Cmd+V paste
 */
async pasteText(text: string, delayMs: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("paste_text", { text, delayMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start meeting recording with live transcription.
 */
async startMeetingRecording(title: string, calendar: MeetingCalendarContext | null, channel: TAURI_CHANNEL<TranscriptionSegment>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_meeting_recording", { title, calendar, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resume recording on an existing meeting and append new transcript segments.
 */
async resumeMeetingRecording(meetingId: string, channel: TAURI_CHANNEL<TranscriptionSegment>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_meeting_recording", { meetingId, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop meeting recording and save transcript.
 * 
 * Decoupled stop: transitions to Stopping, returns the (already-known) meeting
 * id immediately, and drains + saves in the background. Segments were persisted
 * incrementally during the meeting, so the detail view can render right away
 * and reconcile when the `MeetingFinalized` event fires.
 */
async stopMeetingRecording() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_meeting_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all saved meetings
 */
async listMeetings() : Promise<Result<MeetingListItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_meetings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a full meeting transcript by ID
 */
async getMeeting(id: string) : Promise<Result<MeetingTranscript, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a meeting by ID
 */
async deleteMeeting(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename a meeting. Targets the in-memory accumulator while that meeting
 * is still recording (it only reaches the DB at stop), the DB otherwise.
 */
async renameMeeting(id: string, title: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_meeting", { id, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save the user's live meeting notes. Targets the in-memory accumulator
 * while that meeting is still recording (it only reaches the DB at stop),
 * the DB otherwise.
 */
async saveMeetingNotes(id: string, notes: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_meeting_notes", { id, notes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save an edited transcript for a meeting
 */
async saveEditedTranscript(id: string, editedTranscript: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_edited_transcript", { id, editedTranscript }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if Ollama is available and list models
 */
async checkOllama() : Promise<Result<OllamaStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_ollama") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Summarize a meeting transcript using Ollama, streaming results back
 */
async summarizeMeeting(id: string, model: string, channel: TAURI_CHANNEL<SummarizeProgress>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("summarize_meeting", { id, model, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Full-text search across meetings and dictation entries
 */
async searchText(query: string, limit: number | null) : Promise<Result<SearchResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_text", { query, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List dictation history entries
 */
async listDictationEntries(limit: number | null) : Promise<Result<DictationEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_dictation_entries", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a dictation history entry
 */
async addDictationEntry(text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_dictation_entry", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a single dictation entry
 */
async deleteDictationEntry(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_dictation_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear all dictation history
 */
async clearDictationHistory() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_dictation_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the typed application settings.
 */
async getSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save the typed application settings.
 */
async saveSettings(settings: AppSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update shortcut bindings at runtime.
 */
async saveShortcuts(shortcuts: ShortcutSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_shortcuts", { shortcuts }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get current shortcut settings
 */
async getShortcuts() : Promise<Result<ShortcutSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current audio input level (RMS, 0.0–1.0) for waveform visualization
 */
async getAudioLevel() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_level") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether system-audio capture (Core Audio process taps) is available on this OS
 */
async getSystemAudioSupport() : Promise<boolean> {
    return await TAURI_INVOKE("get_system_audio_support");
},
/**
 * Debug: record system audio for `seconds` and write it to a WAV file.
 * Returns the file path. Exercises the tap end-to-end (TCC prompt included).
 */
async debugRecordSystemAudio(seconds: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("debug_record_system_audio", { seconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the current state machine state.
 */
async getMachineState() : Promise<Result<AppStateMachine, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_machine_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Recover from an error state.
 */
async recoverState() : Promise<Result<AppStateMachine, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("recover_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDictionary() : Promise<Result<DictionaryEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_dictionary") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addDictionaryEntry(term: string, phoneticCode: string | null, category: string | null) : Promise<Result<DictionaryEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_dictionary_entry", { term, phoneticCode, category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateDictionaryEntry(id: number, term: string, phoneticCode: string | null, category: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_dictionary_entry", { id, term, phoneticCode, category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDictionaryEntry(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_dictionary_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearDictionary() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_dictionary") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cheap, non-prompting snapshot for the onboarding's initial render.
 */
async getPermissionStatus() : Promise<Result<PermissionStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_permission_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Trigger the native prompt (or open System Settings) for one permission.
 * The probe opens a device, so it runs off the command thread.
 */
async requestPermission(kind: PermissionKind) : Promise<Result<PermState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_permission", { kind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Calendars available for the settings picker. Errors when access is not
 * granted (the picker is only reachable once the permission flow succeeded).
 */
async listCalendars() : Promise<Result<CalendarInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_calendars") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Today's timed events for the home view. Missing permission is a state the
 * UI renders, not an error, so it comes back inside the payload.
 */
async listTodaysCalendarEvents() : Promise<Result<TodayCalendar, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_todays_calendar_events") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
meetingFinalized: MeetingFinalized,
meetingStopRequested: MeetingStopRequested,
navigate: Navigate,
pipelineError: PipelineError,
shortcutPttStart: ShortcutPttStart,
shortcutPttStop: ShortcutPttStop,
shortcutToggle: ShortcutToggle,
stateChanged: StateChanged,
systemAudioStatus: SystemAudioStatus,
transcriptionHealth: TranscriptionHealth,
upcomingMeeting: UpcomingMeeting
}>({
meetingFinalized: "meeting-finalized",
meetingStopRequested: "meeting-stop-requested",
navigate: "navigate",
pipelineError: "pipeline-error",
shortcutPttStart: "shortcut-ptt-start",
shortcutPttStop: "shortcut-ptt-stop",
shortcutToggle: "shortcut-toggle",
stateChanged: "state-changed",
systemAudioStatus: "system-audio-status",
transcriptionHealth: "transcription-health",
upcomingMeeting: "upcoming-meeting"
})

/** user-defined constants **/



/** user-defined types **/

export type AppSettings = { theme: Theme; locale: string; auto_paste: boolean; paste_delay_ms: number; ollama_url: string; ollama_model: string; debug_transcription: boolean; audio_device: string | null; transcription_engine_id: string; transcription_model_id: string; transcription_backend_id: string; vad_enabled: boolean; filler_removal: boolean; stutter_collapse: boolean; dictionary_correction: boolean; 
/**
 * Meeting mode: capture system audio (other participants) alongside
 * the microphone via a Core Audio tap.
 */
capture_system_audio: boolean; 
/**
 * Calendar integration is opt-in: it reads the user's calendar, so it
 * stays off until explicitly enabled (which triggers the TCC prompt).
 */
calendar_integration_enabled: boolean; 
/**
 * Calendars shown in the today list; empty means all calendars.
 */
calendar_selected_ids: string[]; 
/**
 * How long before an event the "start transcription?" reminder fires.
 */
calendar_reminder_minutes: number }
/**
 * Unified application state machine.
 * Replaces scattered `is_recording`, `model_loaded`, `recording_mode`, `active_profile` booleans
 * with a single enum that enforces valid transitions.
 */
export type AppStateMachine = { state: "idle" } | { state: "downloading"; data: { profile: TranscriptionProfile } } | { state: "downloaded"; data: { profile: TranscriptionProfile } } | { state: "loading"; data: { profile: TranscriptionProfile } } | { state: "ready"; data: { profile: TranscriptionProfile } } | { state: "recording_dictation"; data: { profile: TranscriptionProfile; session_id: number } } | { state: "recording_meeting"; data: { profile: TranscriptionProfile; session_id: number; meeting_id: string } } | { state: "stopping"; data: { profile: TranscriptionProfile; was_recording: RecordingKind } } | { state: "unloading"; data: { profile: TranscriptionProfile; next_profile: TranscriptionProfile | null } } | { state: "error"; data: { message: string; recovery: ErrorRecovery } }
export type AppView = "home" | "settings"
/**
 * Info about an available audio input device, sent to frontend
 */
export type AudioDeviceInfo = { name: string; is_default: boolean }
export type AudioInputRequirements = { sample_rate_hz: number; channels: number; chunk_size_samples: number }
/**
 * One occurrence of a calendar event (recurring events arrive pre-expanded).
 */
export type CalendarEvent = { 
/**
 * EKEvent identifier — shared by all occurrences of a recurring event,
 * so dedup keys must combine it with `start`.
 */
id: string; title: string; start: string; end: string; calendar_id: string; calendar_title: string; participants: MeetingParticipant[]; location: string | null; 
/**
 * The event URL — for video meetings this is usually the conference link.
 */
url: string | null }
/**
 * One calendar as shown in the settings picker.
 */
export type CalendarInfo = { id: string; title: string; 
/**
 * Account the calendar belongs to (e.g. "iCloud", "Google"), for grouping.
 */
source_title: string | null }
/**
 * A dictation history entry
 */
export type DictationEntry = { id: string; text: string; timestamp: string }
export type DictionaryEntry = { id: number; term: string; phonetic_code: string | null; category: string | null; created_at: string }
/**
 * Download status reported to the frontend
 */
export type DownloadProgress = { file: string; downloaded_bytes: number; total_bytes: number | null; completed_files: number; total_files: number; status: DownloadStatus }
export type DownloadStatus = "starting" | "downloading" | "complete" | { error: string }
export type ErrorRecovery = "retry_from_idle" | { retry_from_downloaded: { profile: TranscriptionProfile } } | { retry_from_ready: { profile: TranscriptionProfile } }
export type HealthStatus = "healthy" | 
/**
 * Inference is behind real-time, or audio chunks were dropped.
 */
"lagging" | 
/**
 * No frame has been processed for several seconds while audio is queued.
 */
"stalled"
/**
 * Calendar context passed by the frontend when starting a meeting from a
 * calendar event.
 */
export type MeetingCalendarContext = { event_id: string; participants: MeetingParticipant[] }
/**
 * Emitted once a stopped meeting has been fully drained and saved in the
 * background, so the detail view can refresh from the now-complete record.
 * `stop_meeting_recording` returns before this work finishes (decoupled stop),
 * so the UI shows the partially-persisted meeting immediately and reconciles
 * when this arrives.
 */
export type MeetingFinalized = { id: string }
/**
 * Lightweight item for listing meetings
 */
export type MeetingListItem = { id: string; title: string; started_at: string; duration_seconds: number; has_summary: boolean; summary_is_stale: boolean }
/**
 * A calendar attendee captured when a meeting is started from a calendar
 * event. Persisted with the meeting and fed into the summary prompt so the
 * model can attribute statements to real names.
 */
export type MeetingParticipant = { name: string; email: string | null; is_organizer: boolean; is_current_user: boolean }
export type MeetingRecordingSession = { id: string; started_at: string; ended_at: string; duration_seconds: number; start_segment_index: number; end_segment_index: number }
/**
 * Emitted by the floating recording pill (or the tray) to ask the meeting
 * controller in the main window to stop the active meeting through its
 * normal stop pipeline.
 */
export type MeetingStopRequested = null
/**
 * Full meeting transcript stored as JSON
 */
export type MeetingTranscript = { id: string; title: string; started_at: string; ended_at: string | null; duration_seconds: number; transcription_profile: TranscriptionProfile; recording_sessions: MeetingRecordingSession[]; segments: TranscriptionSegment[]; summary: string | null; summary_is_stale: boolean; summary_model: string | null; summary_generated_at: string | null; edited_transcript: string | null; 
/**
 * Free-form notes the user typed during the meeting; fed into the
 * summary prompt.
 */
notes: string | null; 
/**
 * Identifier of the calendar event this meeting was started from.
 */
calendar_event_id: string | null; 
/**
 * Attendees captured from the calendar event; shown in the UI and fed
 * into the summary prompt.
 */
participants: MeetingParticipant[] }
export type ModelArtifactDescriptor = { id: string; label: string; description: string; provider: string; repository: string; revision: string | null; file_format: string; download_size_bytes: number | null; required_files: string[] }
export type Navigate = AppView
export type OllamaModelDescriptor = { id: string; label: string; can_summarize: boolean }
export type OllamaStatus = { available: boolean; base_url: string; models: OllamaModelDescriptor[] }
export type PermState = "granted" | "denied" | 
/**
 * Not yet probed — the user hasn't triggered this one (probing would
 * prompt, so we don't do it unsolicited at startup).
 */
"unknown" | 
/**
 * The OS doesn't support this capability (e.g. taps need macOS 14.4+).
 */
"unsupported"
/**
 * Which capability to probe or prompt for via `request`.
 */
export type PermissionKind = "microphone" | "system_audio" | "accessibility" | "calendar"
export type PermissionStatus = { microphone: PermState; system_audio: PermState; accessibility: PermState; calendar: PermState }
/**
 * Pipeline failure surfaced to the frontend instead of dying silently in logs.
 */
export type PipelineError = { scope: PipelineErrorScope; message: string }
export type PipelineErrorScope = 
/**
 * A single frame failed to transcribe and was skipped.
 */
"frame" | 
/**
 * The session was aborted (e.g. repeated engine failures).
 */
"session"
export type RecordingKind = "dictation" | { meeting: { meeting_id: string } }
/**
 * Search result from FTS5 full-text search
 */
export type SearchResult = { source_type: string; source_id: string; snippet: string; rank: number }
export type ShortcutPttStart = null
export type ShortcutPttStop = null
export type ShortcutSettings = { toggle: string; push_to_talk: string }
export type ShortcutToggle = null
/**
 * Who produced a segment in a diarized meeting: the microphone is the local
 * user (Me), system audio is everyone else (Them). `None` = single-stream
 * session (dictation, or a meeting recorded without diarization).
 */
export type Speaker = "me" | "them"
export type StateChanged = AppStateMachine
export type SummarizeProgress = { text: string; done: boolean }
/**
 * State of the system-audio capture leg of a meeting session, emitted when
 * the session starts and whenever the leg changes (e.g. tap rebuild after
 * an output device switch).
 */
export type SystemAudioStatus = { active: boolean; 
/**
 * Present when inactive because of an error (e.g. permission denied).
 */
reason: string | null }
export type Theme = "dark" | "light" | "system"
/**
 * Today's events plus the permission state, so the UI can render the
 * no-permission case without string-matching errors.
 */
export type TodayCalendar = { permission: PermState; events: CalendarEvent[] }
export type TranscriptionCapabilities = { supports_streaming: boolean; supports_batch_transcription: boolean; supports_language_auto_detect: boolean; supports_word_timestamps: boolean; supports_partial_results: boolean }
export type TranscriptionCatalog = { engines: TranscriptionEngineDescriptor[]; selected_engine_id: string; selected_model_id: string; selected_backend_id: string }
export type TranscriptionEngineDescriptor = { id: string; label: string; description: string; models: TranscriptionModelDescriptor[] }
/**
 * Periodic pipeline health snapshot emitted during recording sessions.
 */
export type TranscriptionHealth = { session_id: number; status: HealthStatus; 
/**
 * Audio chunks waiting in the capture→inference channel.
 */
queue_depth: number; 
/**
 * Age of the most-delayed chunk processed in the last window (ms).
 */
lag_ms: number; 
/**
 * Chunks dropped by the capture callback since the session started.
 */
dropped_chunks: number }
export type TranscriptionModelDescriptor = { id: string; label: string; description: string; download_size_bytes: number | null; recommended_memory_bytes: number | null; supported_languages: string[]; capabilities: TranscriptionCapabilities; audio_input: AudioInputRequirements; available_in_app: boolean; availability_note: string | null; backends: TranscriptionRuntimeBackendDescriptor[]; recommended_backend_id: string }
export type TranscriptionProfile = { engine_id: string; engine_label: string; model_id: string; model_label: string; backend_id?: string; backend_label?: string }
export type TranscriptionProfileSelection = { engine_id: string; model_id: string; backend_id: string }
export type TranscriptionRuntimeBackendDescriptor = { id: string; label: string; description: string; recommended: boolean; available_in_app: boolean; availability_note: string | null; artifacts: ModelArtifactDescriptor[] }
export type TranscriptionRuntimePhase = "download_required" | "load_required" | "ready"
export type TranscriptionRuntimeStatus = { profile: TranscriptionProfile; phase: TranscriptionRuntimePhase; model_dir: string }
/**
 * A piece of transcribed text with metadata
 */
export type TranscriptionSegment = { text: string; start_time: number; end_time: number; is_final: boolean; language: string | null; confidence: number | null; 
/**
 * Set by the pipeline for diarized meetings; `None` otherwise.
 */
speaker?: Speaker | null }
/**
 * Emitted by the calendar reminder scheduler shortly before a calendar
 * event starts, so the frontend can offer a one-click transcription start.
 * A system notification is sent alongside; this event drives the in-app
 * banner (notification clicks are not reliably delivered on macOS).
 */
export type UpcomingMeeting = { event: CalendarEvent; starts_in_seconds: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
