
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Catalog of supported transcription engines and models.
 */
async getTranscriptionCatalog() : Promise<Result<TranscriptionCatalog, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcription_catalog") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check whether the selected transcription model is downloaded and loaded.
 */
async getModelStatus(selection: TranscriptionProfileSelection) : Promise<Result<TranscriptionRuntimeStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_status", { selection }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download the selected transcription model.
 * Progress is streamed back via the Channel API.
 */
async downloadModel(selection: TranscriptionProfileSelection, channel: TAURI_CHANNEL<DownloadProgress>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { selection, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load the model into memory (GPU/CPU). Must be called after download.
 * Also spawns the persistent inference pipeline thread.
 */
async loadModel(selection: TranscriptionProfileSelection) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_model", { selection }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start streaming transcription.
 */
async startTranscription(channel: TAURI_CHANNEL<TranscriptionSegment>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_transcription", { channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop streaming transcription.
 */
async stopTranscription() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_transcription") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List available audio input devices
 */
async listAudioDevices() : Promise<Result<AudioDeviceInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_audio_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Select an audio input device by name
 */
async selectAudioDevice(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("select_audio_device", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Debug: feed the debug WAV through the engine to test model in isolation.
 */
async testTranscribeWav() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_transcribe_wav") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Copy text to clipboard and simulate Cmd+V paste
 */
async pasteText(text: string, delayMs: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("paste_text", { text, delayMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start meeting recording with live transcription.
 */
async startMeetingRecording(title: string, channel: TAURI_CHANNEL<TranscriptionSegment>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_meeting_recording", { title, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resume recording on an existing meeting and append new transcript segments.
 */
async resumeMeetingRecording(meetingId: string, channel: TAURI_CHANNEL<TranscriptionSegment>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_meeting_recording", { meetingId, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop meeting recording and save transcript.
 */
async stopMeetingRecording() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_meeting_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all saved meetings
 */
async listMeetings() : Promise<Result<MeetingListItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_meetings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a full meeting transcript by ID
 */
async getMeeting(id: string) : Promise<Result<MeetingTranscript, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a meeting by ID
 */
async deleteMeeting(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if Ollama is available and list models
 */
async checkOllama() : Promise<Result<OllamaStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_ollama") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Summarize a meeting transcript using Ollama, streaming results back
 */
async summarizeMeeting(id: string, model: string, channel: TAURI_CHANNEL<SummarizeProgress>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("summarize_meeting", { id, model, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List dictation history entries
 */
async listDictationEntries(limit: number | null) : Promise<Result<DictationEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_dictation_entries", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a dictation history entry
 */
async addDictationEntry(text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_dictation_entry", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a single dictation entry
 */
async deleteDictationEntry(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_dictation_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear all dictation history
 */
async clearDictationHistory() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_dictation_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the typed application settings.
 */
async getSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save the typed application settings.
 */
async saveSettings(settings: AppSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update shortcut bindings at runtime.
 */
async saveShortcuts(shortcuts: ShortcutSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_shortcuts", { shortcuts }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get current shortcut settings
 */
async getShortcuts() : Promise<Result<ShortcutSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current audio input level (RMS, 0.0–1.0) for waveform visualization
 */
async getAudioLevel() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_level") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the current state machine state.
 */
async getMachineState() : Promise<Result<AppStateMachine, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_machine_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Recover from an error state.
 */
async recoverState() : Promise<Result<AppStateMachine, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("recover_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
navigate: Navigate,
shortcutPttStart: ShortcutPttStart,
shortcutPttStop: ShortcutPttStop,
shortcutToggle: ShortcutToggle,
stateChanged: StateChanged
}>({
navigate: "navigate",
shortcutPttStart: "shortcut-ptt-start",
shortcutPttStop: "shortcut-ptt-stop",
shortcutToggle: "shortcut-toggle",
stateChanged: "state-changed"
})

/** user-defined constants **/



/** user-defined types **/

export type AppSettings = { theme: Theme; locale: string; auto_paste: boolean; paste_delay_ms: number; ollama_url: string; ollama_model: string; debug_transcription: boolean; audio_device: string | null; transcription_engine_id: string; transcription_model_id: string; transcription_backend_id: string }
/**
 * Unified application state machine.
 * Replaces scattered `is_recording`, `model_loaded`, `recording_mode`, `active_profile` booleans
 * with a single enum that enforces valid transitions.
 */
export type AppStateMachine = { state: "idle" } | { state: "downloading"; data: { profile: TranscriptionProfile } } | { state: "downloaded"; data: { profile: TranscriptionProfile } } | { state: "loading"; data: { profile: TranscriptionProfile } } | { state: "ready"; data: { profile: TranscriptionProfile } } | { state: "recording_dictation"; data: { profile: TranscriptionProfile; session_id: number } } | { state: "recording_meeting"; data: { profile: TranscriptionProfile; session_id: number; meeting_id: string } } | { state: "stopping"; data: { profile: TranscriptionProfile; was_recording: RecordingKind } } | { state: "unloading"; data: { profile: TranscriptionProfile; next_profile: TranscriptionProfile | null } } | { state: "error"; data: { message: string; recovery: ErrorRecovery } }
export type AppView = "transcription" | "meeting" | "meeting-history" | "settings"
/**
 * Info about an available audio input device, sent to frontend
 */
export type AudioDeviceInfo = { name: string; is_default: boolean }
export type AudioInputRequirements = { sample_rate_hz: number; channels: number; chunk_size_samples: number }
/**
 * A dictation history entry
 */
export type DictationEntry = { id: string; text: string; timestamp: string }
/**
 * Download status reported to the frontend
 */
export type DownloadProgress = { file: string; downloaded_bytes: number; total_bytes: number | null; completed_files: number; total_files: number; status: DownloadStatus }
export type DownloadStatus = "starting" | "downloading" | "complete" | { error: string }
export type ErrorRecovery = "retry_from_idle" | { retry_from_downloaded: { profile: TranscriptionProfile } } | { retry_from_ready: { profile: TranscriptionProfile } }
/**
 * Lightweight item for listing meetings
 */
export type MeetingListItem = { id: string; title: string; started_at: string; duration_seconds: number; has_summary: boolean; summary_is_stale: boolean }
export type MeetingRecordingSession = { id: string; started_at: string; ended_at: string; duration_seconds: number; start_segment_index: number; end_segment_index: number }
/**
 * Full meeting transcript stored as JSON
 */
export type MeetingTranscript = { id: string; title: string; started_at: string; ended_at: string | null; duration_seconds: number; transcription_profile: TranscriptionProfile; recording_sessions: MeetingRecordingSession[]; segments: TranscriptionSegment[]; summary: string | null; summary_is_stale: boolean; summary_model: string | null; summary_generated_at: string | null }
export type ModelArtifactDescriptor = { id: string; label: string; description: string; provider: string; repository: string; revision: string | null; file_format: string; download_size_bytes: number | null; required_files: string[] }
export type Navigate = AppView
export type OllamaModelDescriptor = { id: string; label: string; can_summarize: boolean }
export type OllamaStatus = { available: boolean; base_url: string; models: OllamaModelDescriptor[] }
export type RecordingKind = "dictation" | { meeting: { meeting_id: string } }
export type ShortcutPttStart = null
export type ShortcutPttStop = null
export type ShortcutSettings = { toggle: string; push_to_talk: string }
export type ShortcutToggle = null
export type StateChanged = AppStateMachine
export type SummarizeProgress = { text: string; done: boolean }
export type Theme = "dark" | "light" | "system"
export type TranscriptionCapabilities = { supports_streaming: boolean; supports_batch_transcription: boolean; supports_language_auto_detect: boolean; supports_word_timestamps: boolean; supports_partial_results: boolean }
export type TranscriptionCatalog = { engines: TranscriptionEngineDescriptor[]; selected_engine_id: string; selected_model_id: string; selected_backend_id: string }
export type TranscriptionEngineDescriptor = { id: string; label: string; description: string; models: TranscriptionModelDescriptor[] }
export type TranscriptionModelDescriptor = { id: string; label: string; description: string; download_size_bytes: number | null; recommended_memory_bytes: number | null; supported_languages: string[]; capabilities: TranscriptionCapabilities; audio_input: AudioInputRequirements; available_in_app: boolean; availability_note: string | null; backends: TranscriptionRuntimeBackendDescriptor[]; recommended_backend_id: string }
export type TranscriptionProfile = { engine_id: string; engine_label: string; model_id: string; model_label: string; backend_id?: string; backend_label?: string }
export type TranscriptionProfileSelection = { engine_id: string; model_id: string; backend_id: string }
export type TranscriptionRuntimeBackendDescriptor = { id: string; label: string; description: string; recommended: boolean; available_in_app: boolean; availability_note: string | null; artifacts: ModelArtifactDescriptor[] }
export type TranscriptionRuntimePhase = "download_required" | "load_required" | "ready"
export type TranscriptionRuntimeStatus = { profile: TranscriptionProfile; phase: TranscriptionRuntimePhase; model_dir: string }
/**
 * A piece of transcribed text with metadata
 */
export type TranscriptionSegment = { text: string; start_time: number; end_time: number; is_final: boolean; language: string | null; confidence: number | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
