
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Catalog of supported transcription engines and models.
 */
async getTranscriptionCatalog() : Promise<Result<TranscriptionCatalog, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcription_catalog") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check whether the selected transcription model is downloaded and loaded.
 */
async getModelStatus(selection: TranscriptionProfileSelection) : Promise<Result<TranscriptionRuntimeStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_status", { selection }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download the selected transcription model.
 * Progress is streamed back via the Channel API.
 */
async downloadModel(selection: TranscriptionProfileSelection, channel: TAURI_CHANNEL<DownloadProgress>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { selection, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a downloaded model from disk.
 */
async deleteModel(selection: TranscriptionProfileSelection) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { selection }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load the model into memory (GPU/CPU). Must be called after download.
 * The engine actor creates the engine, swaps out any previous one, and
 * loads the weights — all on its own thread.
 */
async loadModel(selection: TranscriptionProfileSelection) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_model", { selection }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start streaming transcription.
 * 
 * `async` + `spawn_blocking`: the engine-reset reply can take 0.5–2s, so the
 * blocking wait runs off-thread and the window never freezes.
 */
async startTranscription(channel: TAURI_CHANNEL<TranscriptionSegment>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_transcription", { channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop streaming transcription.
 * 
 * Awaits the drain so the frontend's assembled transcript (used for clipboard
 * and dictation history) is complete before this resolves. The drain runs in
 * `spawn_blocking`, so awaiting it does not freeze the window.
 */
async stopTranscription() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_transcription") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List available audio input devices
 */
async listAudioDevices() : Promise<Result<AudioDeviceInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_audio_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Select an audio input device by name
 */
async selectAudioDevice(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("select_audio_device", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether this Mac has a battery (i.e. is a laptop). Gates the
 * clamshell-microphone setting in the UI — meaningless on a desktop Mac.
 */
async isLaptop() : Promise<boolean> {
    return await TAURI_INVOKE("is_laptop");
},
/**
 * Debug: feed the debug WAV through the engine to test model in isolation.
 */
async testTranscribeWav() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_transcribe_wav") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Insert dictation text into the active app (clipboard paste or simulated typing).
 */
async pasteText(text: string, delayMs: number, method: PasteMethod) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("paste_text", { text, delayMs, method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start meeting recording with live transcription.
 */
async startMeetingRecording(title: string, calendar: MeetingCalendarContext | null, channel: TAURI_CHANNEL<TranscriptionSegment>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_meeting_recording", { title, calendar, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resume recording on an existing meeting and append new transcript segments.
 */
async resumeMeetingRecording(meetingId: string, channel: TAURI_CHANNEL<TranscriptionSegment>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_meeting_recording", { meetingId, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop meeting recording and save transcript.
 * 
 * Decoupled stop: transitions to Stopping, returns the (already-known) meeting
 * id immediately, and drains + saves in the background. Segments were persisted
 * incrementally during the meeting, so the detail view can render right away
 * and reconcile when the `MeetingFinalized` event fires.
 */
async stopMeetingRecording() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_meeting_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return and clear the meeting id paused by the system-sleep handler, if
 * any. The frontend calls this on `SystemWokeUp` (and again on webview
 * visibility change, belt and braces) to decide whether to offer/auto-start
 * a resume.
 */
async takeSleepPausedMeeting() : Promise<string | null> {
    return await TAURI_INVOKE("take_sleep_paused_meeting");
},
/**
 * List all saved meetings
 */
async listMeetings() : Promise<Result<MeetingListItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_meetings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a full meeting transcript by ID
 */
async getMeeting(id: string) : Promise<Result<MeetingTranscript, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a meeting by ID
 */
async deleteMeeting(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename a meeting. Targets the in-memory accumulator while that meeting
 * is still recording (it only reaches the DB at stop), the DB otherwise.
 */
async renameMeeting(id: string, title: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_meeting", { id, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save the user's live meeting notes. Targets the in-memory accumulator
 * while that meeting is still recording (it only reaches the DB at stop),
 * the DB otherwise.
 */
async saveMeetingNotes(id: string, notes: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_meeting_notes", { id, notes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save an edited transcript for a meeting
 */
async saveEditedTranscript(id: string, editedTranscript: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_edited_transcript", { id, editedTranscript }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Render a meeting export without writing to disk. Used by tests and, if
 * ever needed, a clipboard-copy affordance.
 */
async exportMeetingPreview(id: string, format: ExportFormat) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_meeting_preview", { id, format }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Suggested filename for a meeting export (e.g. `2026-07-09-weekly-sync.md`),
 * used as the save dialog's default path.
 */
async exportMeetingFilename(id: string, format: ExportFormat) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_meeting_filename", { id, format }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Render a meeting export and write it to `path`. The save dialog itself
 * (picking `path`) runs frontend-side via the dialog plugin.
 */
async exportMeetingToFile(id: string, format: ExportFormat, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_meeting_to_file", { id, format, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List available summary providers and models (Ollama + Apple Intelligence).
 */
async checkSummaryProviders() : Promise<Result<SummaryProvidersStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_summary_providers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Summarize a meeting transcript using the selected provider, streaming results back.
 */
async summarizeMeeting(id: string, model: string, channel: TAURI_CHANNEL<SummarizeProgress>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("summarize_meeting", { id, model, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Full-text search across meetings and dictation entries
 */
async searchText(query: string, limit: number | null) : Promise<Result<SearchResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_text", { query, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List dictation history entries
 */
async listDictationEntries(limit: number | null) : Promise<Result<DictationEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_dictation_entries", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a dictation history entry
 */
async addDictationEntry(text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_dictation_entry", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a single dictation entry
 */
async deleteDictationEntry(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_dictation_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear all dictation history
 */
async clearDictationHistory() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_dictation_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Optional LLM polish pass for dictation text before paste/history.
 */
async polishDictation(text: string) : Promise<Result<DictationPolishResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("polish_dictation", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the typed application settings.
 */
async getSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save the typed application settings.
 */
async saveSettings(settings: AppSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update shortcut bindings at runtime.
 */
async saveShortcuts(shortcuts: ShortcutSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_shortcuts", { shortcuts }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get current shortcut settings
 */
async getShortcuts() : Promise<Result<ShortcutSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether system-audio capture (Core Audio process taps) is available on this OS
 */
async getSystemAudioSupport() : Promise<boolean> {
    return await TAURI_INVOKE("get_system_audio_support");
},
/**
 * Debug: record system audio for `seconds` and write it to a WAV file.
 * Returns the file path. Exercises the tap end-to-end (TCC prompt included).
 */
async debugRecordSystemAudio(seconds: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("debug_record_system_audio", { seconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the current state machine state.
 */
async getMachineState() : Promise<Result<AppStateMachine, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_machine_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Recover from an error state.
 */
async recoverState() : Promise<Result<AppStateMachine, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("recover_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDictionary() : Promise<Result<DictionaryEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_dictionary") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addDictionaryEntry(term: string, pronunciation: string | null, category: string | null) : Promise<Result<DictionaryEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_dictionary_entry", { term, pronunciation, category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateDictionaryEntry(id: number, term: string, pronunciation: string | null, category: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_dictionary_entry", { id, term, pronunciation, category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDictionaryEntry(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_dictionary_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearDictionary() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_dictionary") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cheap, non-prompting snapshot for the onboarding's initial render.
 */
async getPermissionStatus() : Promise<Result<PermissionStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_permission_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Trigger the native prompt (or open System Settings) for one permission.
 * The probe opens a device, so it runs off the command thread.
 */
async requestPermission(kind: PermissionKind) : Promise<Result<PermState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_permission", { kind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Calendars available for the settings picker. Errors when access is not
 * granted (the picker is only reachable once the permission flow succeeded).
 */
async listCalendars() : Promise<Result<CalendarInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_calendars") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Today's timed events for the home view. Missing permission is a state the
 * UI renders, not an error, so it comes back inside the payload.
 */
async listTodaysCalendarEvents() : Promise<Result<TodayCalendar, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_todays_calendar_events") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Kick off a full data archive export in a fresh `souffle-export-*` folder
 * under `dest_dir`. Returns as soon as the destination is validated; the
 * actual export runs on a background thread and reports progress through
 * `ArchiveExportProgress` events, since walking every meeting can take a
 * while for a large history.
 */
async exportArchive(destDir: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_archive", { destDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Database size on disk plus meeting/dictation counts, for the Settings >
 * Data stats line.
 */
async getDataStats() : Promise<Result<DataStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_data_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reveal the app's data directory in Finder. Uses the `open` CLI (already
 * the pattern for macOS-only shell-outs in this codebase, see
 * `permissions::open_accessibility_settings` and `calendar::mod`) rather
 * than pulling in the Tauri opener plugin, since this app only ships for
 * macOS and `open` is always available there.
 */
async revealDataDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve the sidecar path and build the copy/paste snippets for Settings >
 * Data. Never fails: an absent binary is a valid (if inactionable) state
 * the UI shows, not an error.
 */
async getMcpSetupInfo() : Promise<Result<McpSetupInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mcp_setup_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spawn the sidecar, perform an MCP `initialize` handshake and `tools/list`
 * call over stdio, and return the discovered tool names joined by ", ".
 * Used by the Settings UI's "Test connection" button as a quick smoke test
 * that the binary actually speaks MCP. `tools/list` alone is intentional:
 * it proves stdio JSON-RPC works without needing a populated database.
 */
async testMcpConnection() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_mcp_connection") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the last N lines from the active rolling log file.
 */
async getLogTail(maxLines: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_tail", { maxLines }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Paths and runtime snapshot for the copy-diagnostics action.
 */
async getDiagnosticsBundle() : Promise<Result<DiagnosticsBundle, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_diagnostics_bundle") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Full diagnostics text (bundle + recent log tail) for clipboard copy.
 */
async getDiagnosticsText() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_diagnostics_text") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check GitHub releases for a newer version. Network errors are returned in
 * the result payload so the UI can show a soft failure.
 */
async checkForUpdates() : Promise<Result<UpdateCheckResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_updates") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Release notes for a specific installed version tag (What's New). Returns
 * `None` when the tag is missing or the network request fails.
 */
async getReleaseNotesForVersion(version: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_release_notes_for_version", { version }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * App version string from the running binary.
 */
async getAppVersion() : Promise<string> {
    return await TAURI_INVOKE("get_app_version");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
archiveExportProgress: ArchiveExportProgress,
audioLevel: AudioLevel,
meetingFinalized: MeetingFinalized,
meetingIdle: MeetingIdle,
meetingStopRequested: MeetingStopRequested,
navigate: Navigate,
pipelineError: PipelineError,
shortcutPttStart: ShortcutPttStart,
shortcutPttStop: ShortcutPttStop,
shortcutToggle: ShortcutToggle,
stateChanged: StateChanged,
systemAudioStatus: SystemAudioStatus,
systemWokeUp: SystemWokeUp,
transcriptionHealth: TranscriptionHealth,
upcomingMeeting: UpcomingMeeting
}>({
archiveExportProgress: "archive-export-progress",
audioLevel: "audio-level",
meetingFinalized: "meeting-finalized",
meetingIdle: "meeting-idle",
meetingStopRequested: "meeting-stop-requested",
navigate: "navigate",
pipelineError: "pipeline-error",
shortcutPttStart: "shortcut-ptt-start",
shortcutPttStop: "shortcut-ptt-stop",
shortcutToggle: "shortcut-toggle",
stateChanged: "state-changed",
systemAudioStatus: "system-audio-status",
systemWokeUp: "system-woke-up",
transcriptionHealth: "transcription-health",
upcomingMeeting: "upcoming-meeting"
})

/** user-defined constants **/



/** user-defined types **/

export type AppSettings = { theme: Theme; locale: string; auto_paste: boolean; paste_delay_ms: number; 
/**
 * How dictation text is inserted: clipboard Cmd+V or simulated keystrokes.
 */
paste_method: PasteMethod; ollama_url: string; ollama_model: string; debug_transcription: boolean; 
/**
 * Global tracing verbosity for the `souffle` crate.
 */
log_level: LogLevel; audio_device: string | null; 
/**
 * Preferred microphone while the lid is closed with an external display
 * attached (clamshell mode). `None` means just follow whatever macOS
 * reports as the default input, the previous behavior.
 */
clamshell_audio_device: string | null; transcription_engine_id: string; transcription_model_id: string; transcription_backend_id: string; vad_enabled: boolean; filler_removal: boolean; stutter_collapse: boolean; dictionary_correction: boolean; 
/**
 * Meeting mode: capture system audio (other participants) alongside
 * the microphone via a Core Audio tap.
 */
capture_system_audio: boolean; 
/**
 * Calendar integration is opt-in: it reads the user's calendar, so it
 * stays off until explicitly enabled (which triggers the TCC prompt).
 */
calendar_integration_enabled: boolean; 
/**
 * Calendars shown in the today list; empty means all calendars.
 */
calendar_selected_ids: string[]; 
/**
 * How long before an event the "start transcription?" reminder fires.
 */
calendar_reminder_minutes: number; 
/**
 * When a calendar event starts and system audio is active, suggest
 * starting a meeting transcription (nudge only, never auto-records).
 */
calendar_autostart_enabled: boolean; 
/**
 * Audible start/stop cues for dictation sessions.
 */
feedback_sounds_enabled: boolean; 
/**
 * Feedback sound volume (0-100).
 */
feedback_sounds_volume: number; 
/**
 * Unload the transcription model after this many idle minutes to
 * reclaim RAM; 0 means never unload. The next recording reloads it
 * through the normal load flow.
 */
model_unload_timeout_minutes: number; 
/**
 * Detect a meeting that has probably ended (no speech for a while, or
 * the max-duration failsafe) and offer/auto-stop. A session snapshots
 * these settings at start; changes apply from the next meeting.
 */
meeting_autostop_enabled: boolean; 
/**
 * Silence duration (minutes) before the meeting is considered idle.
 */
meeting_autostop_minutes: number; 
/**
 * Hard failsafe: stop the meeting after this many minutes regardless of
 * speech activity.
 */
meeting_max_duration_minutes: number; 
/**
 * Optional LLM post-processing applied to dictation before paste/history.
 */
dictation_polish_enabled: boolean; 
/**
 * Active polish template id (email, bullets, no_fillers).
 */
dictation_polish_template_id: string; 
/**
 * User-editable polish prompt templates.
 */
dictation_polish_templates: DictationPolishTemplate[]; 
/**
 * App version the user has acknowledged (What's New / post-update dialog).
 */
last_seen_version: string }
/**
 * Unified application state machine.
 * Replaces scattered `is_recording`, `model_loaded`, `recording_mode`, `active_profile` booleans
 * with a single enum that enforces valid transitions.
 */
export type AppStateMachine = { state: "idle" } | { state: "downloading"; data: { profile: TranscriptionProfile } } | { state: "downloaded"; data: { profile: TranscriptionProfile } } | { state: "loading"; data: { profile: TranscriptionProfile } } | { state: "ready"; data: { profile: TranscriptionProfile } } | { state: "recording_dictation"; data: { profile: TranscriptionProfile; session_id: number } } | { state: "recording_meeting"; data: { profile: TranscriptionProfile; session_id: number; meeting_id: string } } | { state: "stopping"; data: { profile: TranscriptionProfile; was_recording: RecordingKind } } | { state: "unloading"; data: { profile: TranscriptionProfile; next_profile: TranscriptionProfile | null } } | { state: "error"; data: { message: string; recovery: ErrorRecovery } }
export type AppView = "home" | "settings"
/**
 * Progress for a full data archive export (`commands::data::export_archive`),
 * which runs on a background thread so the command itself returns
 * immediately. Emitted once per meeting processed, plus a final event with
 * `finished: true`. `error` carries a fatal, whole-archive failure (e.g. the
 * destination became unwritable); a single bad meeting is not fatal, it is
 * only reflected in the written manifest's `errors` count.
 */
export type ArchiveExportProgress = { done: number; total: number; finished: boolean; error: string | null }
/**
 * Info about an available audio input device, sent to frontend
 */
export type AudioDeviceInfo = { name: string; is_default: boolean }
export type AudioInputRequirements = { sample_rate_hz: number; channels: number; chunk_size_samples: number }
/**
 * Current microphone/meeting input level (RMS, 0.0-1.0), pushed by the audio
 * thread while a capture session is active so the waveform UI doesn't need
 * to poll `get_audio_level` over IPC.
 */
export type AudioLevel = { level: number }
/**
 * One occurrence of a calendar event (recurring events arrive pre-expanded).
 */
export type CalendarEvent = { 
/**
 * EKEvent identifier — shared by all occurrences of a recurring event,
 * so dedup keys must combine it with `start`.
 */
id: string; title: string; start: string; end: string; calendar_id: string; calendar_title: string; participants: MeetingParticipant[]; location: string | null; 
/**
 * The event URL — for video meetings this is usually the conference link.
 */
url: string | null; 
/**
 * The invitation body (EKCalendarItem notes). Mined for session-scoped
 * transcription hints when a meeting starts from this event.
 */
description: string | null }
/**
 * One calendar as shown in the settings picker.
 */
export type CalendarInfo = { id: string; title: string; 
/**
 * Account the calendar belongs to (e.g. "iCloud", "Google"), for grouping.
 */
source_title: string | null }
export type CalendarMeetingNudgeKind = 
/**
 * Pre-event reminder inside the configured lead-time window.
 */
"reminder" | 
/**
 * At-event-time suggestion when system audio is active but no recording runs.
 */
"autostart"
/**
 * Settings > Data stats line: database size and row counts.
 */
export type DataStats = { db_size_bytes: number; meeting_count: number; dictation_count: number }
export type DiagnosticsBundle = { app_version: string; data_dir: string; log_dir: string; log_file: string | null; db_path: string; models_dir: string; machine_state: string; log_level: string; debug_transcription: boolean }
/**
 * A dictation history entry
 */
export type DictationEntry = { id: string; text: string; timestamp: string }
export type DictationPolishResult = { text: string; 
/**
 * True when polish was skipped (disabled, blank input, or no provider).
 */
skipped: boolean; 
/**
 * Set when polish was attempted but failed; the returned text is the
 * pre-polish input (after invisible-char stripping).
 */
warning: string | null }
export type DictationPolishTemplate = { id: string; label: string; prompt: string }
export type DictionaryEntry = { id: number; term: string; 
/**
 * How the term sounds when spoken, spelled out (e.g. "vésix" for "V6").
 * Drives phonetic matching; when absent, the term's own Soundex is used
 * (except for digit-bearing terms, whose Soundex is meaningless).
 */
pronunciation: string | null; category: string | null; created_at: string }
/**
 * Download status reported to the frontend
 */
export type DownloadProgress = { file: string; downloaded_bytes: number; total_bytes: number | null; completed_files: number; total_files: number; status: DownloadStatus }
export type DownloadStatus = "starting" | "downloading" | "complete" | { error: string }
export type ErrorRecovery = "retry_from_idle" | { retry_from_downloaded: { profile: TranscriptionProfile } } | { retry_from_ready: { profile: TranscriptionProfile } }
export type ExportFormat = "markdown" | "json" | "srt" | "vtt"
export type HealthStatus = "healthy" | 
/**
 * Inference is behind real-time, or audio chunks were dropped.
 */
"lagging" | 
/**
 * No frame has been processed for several seconds while audio is queued.
 */
"stalled"
export type LogLevel = "error" | "warn" | "info" | "debug" | "trace"
export type McpSetupInfo = { binary_path: string; exists: boolean; claude_desktop_snippet: string; claude_code_command: string }
/**
 * Calendar context passed by the frontend when starting a meeting from a
 * calendar event.
 */
export type MeetingCalendarContext = { event_id: string; participants: MeetingParticipant[]; 
/**
 * Invitation body; mined for session-scoped transcription hints at
 * start, not persisted.
 */
description?: string | null }
/**
 * Emitted once a stopped meeting has been fully drained and saved in the
 * background, so the detail view can refresh from the now-complete record.
 * `stop_meeting_recording` returns before this work finishes (decoupled stop),
 * so the UI shows the partially-persisted meeting immediately and reconciles
 * when this arrives.
 */
export type MeetingFinalized = { id: string }
/**
 * A meeting recording session looks like it has ended: either speech has
 * stopped for a while, or the session hit the max-duration failsafe. Drives
 * the live-card banner; a system notification is also sent on the first
 * occurrence (see `pipeline::idle::MeetingIdleSignal::first`).
 */
export type MeetingIdle = { reason: MeetingIdleReason; idle_seconds: number; threshold_seconds: number }
export type MeetingIdleReason = 
/**
 * No transcript segment with text for the configured silence threshold.
 */
"silence" | 
/**
 * The session has run past the configured max-duration failsafe.
 */
"max_duration"
/**
 * Lightweight item for listing meetings
 */
export type MeetingListItem = { id: string; title: string; started_at: string; duration_seconds: number; has_summary: boolean; summary_is_stale: boolean }
/**
 * A calendar attendee captured when a meeting is started from a calendar
 * event. Persisted with the meeting and fed into the summary prompt so the
 * model can attribute statements to real names.
 */
export type MeetingParticipant = { name: string; email: string | null; is_organizer: boolean; is_current_user: boolean }
export type MeetingRecordingSession = { id: string; started_at: string; ended_at: string; duration_seconds: number; start_segment_index: number; end_segment_index: number }
/**
 * Emitted by the floating recording pill (or the tray) to ask the meeting
 * controller in the main window to stop the active meeting through its
 * normal stop pipeline.
 */
export type MeetingStopRequested = null
/**
 * Full meeting transcript stored as JSON
 */
export type MeetingTranscript = { id: string; title: string; started_at: string; ended_at: string | null; duration_seconds: number; transcription_profile: TranscriptionProfile; recording_sessions: MeetingRecordingSession[]; segments: TranscriptionSegment[]; summary: string | null; summary_is_stale: boolean; summary_model: string | null; summary_generated_at: string | null; structured_summary: StructuredSummary | null; edited_transcript: string | null; 
/**
 * Free-form notes the user typed during the meeting; fed into the
 * summary prompt.
 */
notes: string | null; 
/**
 * Identifier of the calendar event this meeting was started from.
 */
calendar_event_id: string | null; 
/**
 * Attendees captured from the calendar event; shown in the UI and fed
 * into the summary prompt.
 */
participants: MeetingParticipant[] }
export type ModelArtifactDescriptor = { id: string; label: string; description: string; provider: string; repository: string; revision: string | null; file_format: string; download_size_bytes: number | null; required_files: string[] }
export type Navigate = AppView
export type PasteMethod = "clipboard" | "type"
export type PermState = "granted" | "denied" | 
/**
 * Not yet probed — the user hasn't triggered this one (probing would
 * prompt, so we don't do it unsolicited at startup).
 */
"unknown" | 
/**
 * The OS doesn't support this capability (e.g. taps need macOS 14.4+).
 */
"unsupported"
/**
 * Which capability to probe or prompt for via `request`.
 */
export type PermissionKind = "microphone" | "system_audio" | "accessibility" | "calendar"
export type PermissionStatus = { microphone: PermState; system_audio: PermState; accessibility: PermState; calendar: PermState }
/**
 * Pipeline failure surfaced to the frontend instead of dying silently in logs.
 */
export type PipelineError = { scope: PipelineErrorScope; message: string }
export type PipelineErrorScope = 
/**
 * A single frame failed to transcribe and was skipped.
 */
"frame" | 
/**
 * The session was aborted (e.g. repeated engine failures).
 */
"session"
export type RecordingKind = "dictation" | { meeting: { meeting_id: string } }
/**
 * Search result from FTS5 full-text search
 */
export type SearchResult = { source_type: string; source_id: string; snippet: string; rank: number }
export type ShortcutPttStart = null
export type ShortcutPttStop = null
export type ShortcutSettings = { toggle: string; push_to_talk: string }
export type ShortcutToggle = null
/**
 * Who produced a segment in a diarized meeting: the microphone is the local
 * user (Me), system audio is everyone else (Them). `None` = single-stream
 * session (dictation, or a meeting recorded without diarization).
 */
export type Speaker = "me" | "them"
export type StateChanged = AppStateMachine
/**
 * A single action item extracted from a meeting summary pass.
 */
export type StructuredActionItem = { text: string; owner: string | null }
/**
 * Typed structured summary: decisions, action items, open questions.
 */
export type StructuredSummary = { decisions?: string[]; action_items?: StructuredActionItem[]; open_questions?: string[] }
export type SummarizeProgress = { text: string; done: boolean }
export type SummaryModelDescriptor = { id: string; label: string; provider: SummaryProviderKind; can_summarize: boolean }
export type SummaryProviderKind = "ollama" | "apple_intelligence"
export type SummaryProvidersStatus = { ollama_url: string; ollama_available: boolean; apple_intelligence_available: boolean; 
/**
 * True when this build linked the Apple Intelligence stub (no FoundationModels).
 */
apple_intelligence_is_stub: boolean; models: SummaryModelDescriptor[] }
/**
 * State of the system-audio capture leg of a meeting session, emitted when
 * the session starts and whenever the leg changes (e.g. tap rebuild after
 * an output device switch).
 */
export type SystemAudioStatus = { active: boolean; 
/**
 * Present when inactive because of an error (e.g. permission denied).
 */
reason: string | null }
/**
 * The system finished sleeping and woke back up (`NSWorkspaceDidWakeNotification`).
 * The frontend calls `take_sleep_paused_meeting` on receiving this (and again
 * on webview visibility change, in case the webview itself was suspended
 * when this fired) to see whether a meeting was paused by sleep and, if so,
 * offer to resume it.
 */
export type SystemWokeUp = null
export type Theme = "dark" | "light" | "system"
/**
 * Today's events plus the permission state, so the UI can render the
 * no-permission case without string-matching errors.
 */
export type TodayCalendar = { permission: PermState; events: CalendarEvent[] }
export type TranscriptionCapabilities = { supports_streaming: boolean; supports_batch_transcription: boolean; supports_language_auto_detect: boolean; supports_word_timestamps: boolean; supports_partial_results: boolean }
export type TranscriptionCatalog = { engines: TranscriptionEngineDescriptor[]; selected_engine_id: string; selected_model_id: string; selected_backend_id: string }
export type TranscriptionEngineDescriptor = { id: string; label: string; description: string; models: TranscriptionModelDescriptor[] }
/**
 * Periodic pipeline health snapshot emitted during recording sessions.
 */
export type TranscriptionHealth = { session_id: number; status: HealthStatus; 
/**
 * Audio chunks waiting in the capture→inference channel.
 */
queue_depth: number; 
/**
 * Age of the most-delayed chunk processed in the last window (ms).
 */
lag_ms: number; 
/**
 * Chunks dropped by the capture callback since the session started.
 */
dropped_chunks: number }
export type TranscriptionModelDescriptor = { id: string; label: string; description: string; download_size_bytes: number | null; recommended_memory_bytes: number | null; supported_languages: string[]; capabilities: TranscriptionCapabilities; audio_input: AudioInputRequirements; available_in_app: boolean; availability_note: string | null; backends: TranscriptionRuntimeBackendDescriptor[]; recommended_backend_id: string }
export type TranscriptionProfile = { engine_id: string; engine_label: string; model_id: string; model_label: string; backend_id?: string; backend_label?: string }
export type TranscriptionProfileSelection = { engine_id: string; model_id: string; backend_id: string }
export type TranscriptionRuntimeBackendDescriptor = { id: string; label: string; description: string; recommended: boolean; available_in_app: boolean; availability_note: string | null; artifacts: ModelArtifactDescriptor[] }
export type TranscriptionRuntimePhase = "download_required" | "load_required" | "ready"
export type TranscriptionRuntimeStatus = { profile: TranscriptionProfile; phase: TranscriptionRuntimePhase; model_dir: string }
/**
 * A piece of transcribed text with metadata
 */
export type TranscriptionSegment = { text: string; start_time: number; end_time: number; is_final: boolean; language: string | null; confidence: number | null; 
/**
 * Set by the pipeline for diarized meetings; `None` otherwise.
 */
speaker?: Speaker | null }
/**
 * Emitted by the calendar reminder scheduler shortly before a calendar
 * event starts, so the frontend can offer a one-click transcription start.
 * A system notification is sent alongside; this event drives the in-app
 * banner (notification clicks are not reliably delivered on macOS).
 */
export type UpcomingMeeting = { event: CalendarEvent; starts_in_seconds: number; kind?: CalendarMeetingNudgeKind }
export type UpdateCheckResult = { current_version: string; latest_version: string | null; update_available: boolean; release_notes: string | null; release_url: string | null; check_error: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
