export type {
  AppSettings,
  AppStateMachine,
  AppView,
  ArchiveExportProgress,
  AudioInputDevice,
  AudioInputRequirements,
  CalendarEvent,
  CalendarInfo,
  DataStats,
  DiagnosticsBundle,
  DictationEntry,
  DictationLiveText,
  DictationPolishResult,
  DictationPolishTemplate,
  DictionaryEntry,
  DownloadProgress,
  DownloadStatus,
  ErrorRecovery,
  ExportFormat,
  LogLevel,
  MeetingAudioRetention,
  MeetingAudioSession,
  MeetingCalendarContext,
  MeetingIdle,
  MeetingIdleReason,
  McpSetupInfo,
  PasteMethod,
  MeetingListItem,
  MeetingParticipant,
  MeetingRecordingSession,
  MeetingTranscript,
  ModelArtifactDescriptor,
  OllamaPullProgress,
  SummaryModelDescriptor,
  SummaryProvidersStatus,
  SummaryTemplate,
  PermState,
  PermissionKind,
  PermissionStatus,
  PillHoldChanged,
  PillHoldKind,
  RecordingKind,
  ShortcutSettings,
  SummarizeProgress,
  Theme,
  TodayCalendar,
  TodayCalendarUpdated,
  UpcomingMeeting,
  CalendarMeetingNudgeKind,
  HealthStatus,
  InputPriority,
  KnownDevice,
  InputRouteNotice,
  InputRouteReason,
  PipelineError,
  TransportType,
  SystemAudioStatus,
  TranscriptionHealth,
  TranscriptionCapabilities,
  TranscriptionCatalog,
  TranscriptionEngineDescriptor,
  TranscriptionModelDescriptor,
  TranscriptionProfile,
  TranscriptionProfileSelection,
  TranscriptionRuntimePhase,
  TranscriptionRuntimeBackendDescriptor,
  TranscriptionRuntimeStatus,
  TranscriptionSegment,
  SearchResult,
  UpdateCheckResult,
} from "./generated";

/** Who produced a transcript segment: "me" (microphone) or "them"
 * (system audio). Backend wire format (see `engine::Speaker` in Rust);
 * specta emits it as a plain `string`. Compare with `===`. */
export type Speaker = string;
