export type {
  AppSettings,
  AppStateMachine,
  AppView,
  ArchiveExportProgress,
  AudioInputDevice,
  AudioInputRequirements,
  CalendarEvent,
  CalendarInfo,
  DataStats,
  DiagnosticsBundle,
  DictationEntry,
  DictationLiveText,
  DictationPolishResult,
  DictationPolishTemplate,
  DictionaryEntry,
  DiarizationProgress,
  DownloadProgress,
  DownloadStatus,
  ErrorRecovery,
  ExportFormat,
  LogLevel,
  MeetingAudioRetention,
  MeetingAudioSession,
  MeetingCalendarContext,
  MeetingDiarized,
  MeetingIdle,
  MeetingIdleReason,
  McpSetupInfo,
  PasteMethod,
  MeetingListItem,
  MeetingParticipant,
  MeetingRecordingSession,
  MeetingSpeaker,
  MeetingTranscript,
  RetagMeetingSpeakerRequest,
  ModelArtifactDescriptor,
  SummaryModelDescriptor,
  SummaryProvidersStatus,
  SummaryTemplate,
  PermState,
  PermissionKind,
  PermissionStatus,
  PillHoldChanged,
  PillHoldKind,
  RecordingKind,
  ShortcutSettings,
  SummarizeProgress,
  Theme,
  TodayCalendar,
  UpcomingMeeting,
  CalendarMeetingNudgeKind,
  HealthStatus,
  PipelineError,
  SystemAudioStatus,
  TranscriptionHealth,
  TranscriptionCapabilities,
  TranscriptionCatalog,
  TranscriptionEngineDescriptor,
  TranscriptionModelDescriptor,
  TranscriptionProfile,
  TranscriptionProfileSelection,
  TranscriptionRuntimePhase,
  TranscriptionRuntimeBackendDescriptor,
  TranscriptionRuntimeStatus,
  TranscriptionSegment,
  SearchResult,
  UpdateCheckResult,
} from "./generated";

/** Who produced a transcript segment: "me", "them", or a persistent
 * cross-meeting speaker identity encoded as `spk:<id>`. Backend wire format
 * (see `engine::Speaker` in Rust); specta emits it as a plain `string`
 * rather than a named union so the `spk:<id>` case doesn't need a literal
 * type per id. Compare with `===` and use as a `Record` key like any string;
 * resolve a persistent id's display name via a meeting's `speakers` list
 * (see `resolveSpeakerLabel` in `../utils/speaker-label`). */
export type Speaker = string;
